name: Jijon
version: 1.0
main: com.onruntime.jijon.Jijon
api-version: 1.19

commands:
  warp:
    aliases: [setwarp, delwarp, warps]
    description: Warp command
    usage: "§cUsage : /[warp/setwarp/delwarp/warps] <arg>"
  clan:
    description: Clan command
    usage: "§cUsage : /[clan/c] <arg>"
